language: go

go:
  - 1.x

before_install:
  - go get -t -v ./...
  - nvm install v10.1.0 --latest-npm
  - npm install

script:
  - make test
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false